# This rule is not used by the project kubevirt-migration-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the migrations.kubevirt.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-migration-controller
    app.kubernetes.io/managed-by: kustomize
  name: migmigration-editor-role
rules:
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migmigrations/status
  verbs:
  - get
