---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - kubevirts
  verbs:
  - list
  - watch
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migclusters
  - migmigrations
  - migplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migclusters/finalizers
  - migmigrations/finalizers
  - migplans/finalizers
  verbs:
  - update
- apiGroups:
  - migrations.kubevirt.io
  resources:
  - migclusters/status
  - migmigrations/status
  - migplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
  - watch
