apiVersion: migrations.kubevirt.io/v1alpha1
kind: MigPlan
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-migration-controller
    app.kubernetes.io/managed-by: kustomize
  name: migplan-sample
spec:
  destMigClusterRef:
    name: migcluster-sample
    namespace: default
  namespaces:
  - vms-lab
  srcMigClusterRef:
    name: migcluster-sample
    namespace: default
